// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYZzJd3yiSCD-HTSUNPOYGfysdeIE9NU',
    appId: '1:462955118580:web:3fbf5c1659cfcaf23b03a1',
    messagingSenderId: '462955118580',
    projectId: 'social-media-app-bcb99',
    authDomain: 'social-media-app-bcb99.firebaseapp.com',
    databaseURL: 'https://social-media-app-bcb99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-media-app-bcb99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN7-cGRVfcYZ4DjKF4NyzzXcpNLg22l_U',
    appId: '1:462955118580:android:8edc89147ac50e3c3b03a1',
    messagingSenderId: '462955118580',
    projectId: 'social-media-app-bcb99',
    databaseURL: 'https://social-media-app-bcb99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-media-app-bcb99.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJYZzJd3yiSCD-HTSUNPOYGfysdeIE9NU',
    appId: '1:462955118580:web:a8046eb10894f9493b03a1',
    messagingSenderId: '462955118580',
    projectId: 'social-media-app-bcb99',
    authDomain: 'social-media-app-bcb99.firebaseapp.com',
    databaseURL: 'https://social-media-app-bcb99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-media-app-bcb99.appspot.com',
  );
}
